import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-white h-screen text-black">
      <Head>
        <title>Book Rosa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>salve salve</div>
    </div>
  );
}
