import Head from "next/head";
import Image from "next/image";

import botaoX from "../assets/botaox.svg";
import botaoVoltar from "../assets/botaoVoltar.svg";
import botaoCoracao from "../assets/botaoCoracao.svg";
import React, { useEffect } from "react";
import supabase from "../utils/supabase";
import { useRouter } from "next/router";

export default function Home() {
  const [escortCount, setescortCount] = React.useState(0);
  const [url, seturl] = React.useState<string>();
  const [AllEscorts, setAllEscorts] = React.useState<Array<any>>([]);

  const router = useRouter();

  const getAllEscorts = async () => {
    let { data: acompanhantes, error } = await supabase
      .from("acompanhantes")
      .select("*");

    if (acompanhantes) {
      // console.log(acompanhantes);
      setAllEscorts(acompanhantes);
    }
  };

  const getImage = async () => {
    console.log("length " + AllEscorts.length);
    const { data } = supabase.storage
      .from("photos")
      .getPublicUrl(
        `${AllEscorts[escortCount]?.nome}/${AllEscorts[escortCount]?.nome}001`
      );

    if (data) {
      // console.log(data);
      seturl(data?.publicUrl);
    }
  };

  useEffect(() => {
    getImage();
  }, [escortCount, AllEscorts]);

  useEffect(() => {
    getAllEscorts();
  }, []);

  return (
    <div className="container mx-auto px-2 text-black ">
      <Head>
        <title>Book Rosa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center pt-2">Logo</div>
      <div>
        <div>
          <div
            id="image"
            className="z-0 relative my-10 bg-transparent h-[635px]"
          >
            {/*eslint-disable-next-line @next/next/no-img-element */}
            <div className="flex justify-center">
              <img src={url} alt="" className="rounded-3xl h-[635px]" />
            </div>

            {/* <Image
              src={
                url
                  ? url
                  : "https://viudhkddfyymxinmimyo.supabase.co/storage/v1/object/public/photos/default/default"
              }
              alt=""
              className="z-10 rounded-3xl"
              fill={true}
            /> */}

            <div
              id="botão"
              className="z-10 flex flex-wrap items-end px-5 -mt-28"
            >
              <div className="flex items-end z-10 h-5/6">
                <div>
                  <h1 className="relative text-white text-4xl font-semibold">
                    {AllEscorts[escortCount]?.nome}{" "}
                    <span className="text-3xl">
                      {AllEscorts[escortCount]?.idade}
                    </span>
                  </h1>
                  <h3 className="relative text-white text-xl">
                    @{AllEscorts[escortCount]?.social_midia}
                  </h3>
                </div>
              </div>

              <div className="grid grid-cols-2 z-10 -mb-10 w-full ">
                <div
                  id="voltar"
                  className="w-full flex justify-start"
                  onClick={() => {
                    if (escortCount === 0) {
                      setescortCount(0);
                    } else {
                      let index = escortCount - 1;
                      setescortCount(index);
                    }
                  }}
                >
                  <Image
                    src={botaoVoltar}
                    alt=""
                    className="rounded-full drop-shadow-xl"
                  />
                </div>

                <div
                  id="x"
                  onClick={() => {
                    console.log("length " + AllEscorts.length);

                    if (escortCount + 1 === AllEscorts.length) {
                      setescortCount(0);
                    } else {
                      let index = escortCount + 1;
                      setescortCount(index);
                    }
                  }}
                  className="w-full flex justify-end"
                >
                  <Image
                    src={botaoX}
                    alt=""
                    className="rounded-full drop-shadow-xl"
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            onClick={() =>
              router.push(`/profile/${AllEscorts[escortCount]?.id}`)
            }
            className="-mt-5 w-full flex justify-center"
          >
            <Image
              src={botaoCoracao}
              className="rounded-full drop-shadow-xl"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  );
}
